MvcBlog/Controllers/HeadingController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlog.Controllers
{
    public class HeadingController : Controller
    {
        // GET: Heading
        HeadingManager hm = new HeadingManager(new EfHeadingDal());
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        WriterManager wm = new WriterManager(new EfWriterDal());
        public ActionResult Index()
        {
            var headingvalues = hm.GetList();
            return View(headingvalues);
        }
        [HttpGet]
        public ActionResult AddHeading()
        {
            List<SelectListItem> valuecategory = (from x in cm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString()
                                                  }).ToList();

            List<SelectListItem> valuewriter = (from x in wm.GetList()
                                                select new SelectListItem
                                                {
                                                    Text = x.WriterName + " " + x.WriterSurName,
                                                    Value = x.WriterID.ToString()
                                                }).ToList();
            ViewBag.vlc = valuecategory;
            ViewBag.vlw = valuewriter;
            return View();
        }

        [HttpPost]
        public ActionResult AddHeading(Heading p)
        {
            p.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            hm.HeadingAdd(p);
            return RedirectToAction("Index");
        }
    }
}

MvcBlog/Views/Heading/AddHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "AddHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yeni Başlık Ekleme</h1>
<br />
@using (Html.BeginForm("AddHeading", "Heading", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = " form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName)
        <br />
        @Html.Label("Kategori")
        @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
        <br />
        @Html.Label("Yazar")
        @Html.DropDownListFor(x => x.WriterID, (List<SelectListItem>)ViewBag.vlw, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterID)
        <br />
        <button class="btn btn-info">Başlığı Oluştur</button>
    </div>
}

MvcBlog/Views/Heading/Index.cshtml
@using EntityLayer.Concrete
@model List<Heading>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Başlık</th>
        <th>Kategori</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.HeadingID</td>
            <td>@item.HeadingName</td>
            <td>@item.Category.CategoryName</td>
        </tr>
    }
</table>
<br />
<a href="/Heading/AddHeading" class="btn btn-info">Yeni Başlık Girişi</a>